### ISSUE TITLE
Unable to run run any example/demo

### ISSUE THREAD

**Issue by alexdantas** [masterzora/tawny-cdk#1]
Hiya, that was an awesome idea to port CDK to Ruby.
I'm curious, which Ruby version was used to run this lib? Also, what pre-requisites does this lib has besides ncurses-ruby?

Here's my thing... I've downloaded the last screenshot from git but couldn't run.

I tried with ruby1.8 but it doesn't have `require_relative`.
I tried with ruby1.9.1 but it keeps sending me this message:

/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- ncurses_bin.so (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /usr/lib/ruby/vendor_ruby/ncurses.rb:22:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /tmp/COISAS_LEGAIS/tawny-cdk-master/lib/cdk.rb:28:in`<top (required)>'
    from /tmp/COISAS_LEGAIS/tawny-cdk-master/examples/example.rb:3:in `require_relative'
    from /tmp/COISAS_LEGAIS/tawny-cdk-master/examples/example.rb:3:in`<top (required)>'
    from examples/label_ex.rb:2:in `require_relative'
    from examples/label_ex.rb:2:in`<main>'

This keeps happening even when I did install (with gem1.9.1) ncurses-ruby, ncurses and rbcurse.
Since I'm at Ubuntu, I also installed pretty much anything that even remotely resembles ncurses (sudo apt-get install ncurses*).

This kept me busy for hours D:

**Comment by alexdantas** [comment]
Trying everything I could, apparently I got it fixed it on Ubuntu 12.04 by installing the gem `snowleopard-ncurses`.
That's very strange, could you tell me how did you set up you machine to make tawny-cdk work?

**Comment by masterzora** [comment]
I'm on an Arch Linux system with Ruby 1.9.3 and Ncurses 5.9-4 both installed via the package manager and http://ncurses-ruby.berlios.de/ installed from source.  I do have better portability somewhere in the roadmap but for now hopefully installing the equivalent packages for one's own distribution should be sufficient.

**Comment by alexdantas** [comment]
Strangely enough, 7 months after this issue I'm on Arch Linux with Ruby 2.0.0 :)

With the latest commit (to make a gem for `tawny-cdk`), more portability is added since `require_relative` is not needed anymore.
