### ISSUE TITLE
tawny-cdk crashes at entry widget example

### ISSUE THREAD

**Issue by alexdantas** [masterzora/tawny-cdk#2]
Whenever I create an entry widget (even on the example `entry_ex.rb` distributed with the library), if I press `Ctrl+N`, the program crashes leaving the following error message:

```
/home/kure/prog/ruby/libs/tawny-cdk/lib/cdk/cdk_objs.rb:251:in `getc': uninitialized constant Ncurses::KEY_TAB (NameError)
from /home/kure/prog/ruby/libs/tawny-cdk/lib/cdk/cdk_objs.rb:261:in `getch'
from /home/kure/prog/ruby/libs/tawny-cdk/lib/cdk/entry.rb:155:in `activate'
from ../libs/tawny-cdk/examples/entry_ex.rb:58:in `main'
from ../libs/tawny-cdk/examples/entry_ex.rb:93:in `<main>'
```

**Comment by masterzora** [comment]
Hey, thanks for trying out the package and submitting bugs.  As my commit history shows, I've been a bit busy with other things to keep up as active development as before but I do hope to be able to get back on actively working on some of the large outstanding issues.

The latest commit fixes this bug and I'll try to respond quickly to any more that you happen to find.

Thanks again!
